const {chromium}=require('playwright'),{fixture,origin}=require('./fixtures.cjs');
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
(async()=>{
 const server=http.createServer((req,res)=>{try{const file=path.resolve('.','.'+new URL(req.url,origin).pathname);res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(8000,'127.0.0.1',r));
 const browser=await chromium.launch({executablePath:process.env.TEST_BROWSER_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});const results=[];
 try{for(const width of [1440,390]){
 const ctx=await browser.newContext({viewport:{width,height:960}});await fixture(ctx);const page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));let fail=false;
 await ctx.route('https://data-api.binance.vision/**',r=>{if(fail)return r.fulfill({status:429,json:{error:'rate limit'}});const u=new URL(r.request().url());const end=Math.floor(Date.now()/900000)*900000;return r.fulfill({json:u.pathname.includes('klines')?Array.from({length:120},(_,i)=>[end-(120-i)*900000,100,102,99,101]):{symbol:u.searchParams.get('symbol'),lastPrice:'101',highPrice:'102',lowPrice:'99',priceChangePercent:'1',closeTime:Date.now()}});});
 await ctx.route('https://api.kraken.com/**',r=>{const u=new URL(r.request().url()),end=Math.floor(Date.now()/900000)*900;return r.fulfill({json:{error:[],result:{XXBTZUSD:u.pathname.includes('OHLC')?Array.from({length:120},(_,i)=>[end-(120-i)*900,200,202,199,201]):{c:['201'],h:['202','202'],l:['199','199']}}}});});
 await ctx.route('https://api.india.delta.exchange/**',r=>r.fulfill({json:{success:true,result:[{symbol:'BTCUSD',contract_type:'perpetual_futures',mark_price:'101',oi_value:'999',oi_value_usd:'50000',timestamp:Date.now()*1000,quotes:{best_bid:'100',best_ask:'102'}}]}}));
 await page.goto(origin+'/crypto.html');await page.locator('#lastPrice').filter({hasText:'101 USDT'}).waitFor();await page.locator('#cryptoChart svg').waitFor();
 assert.equal(await page.locator('#dayChange').innerText(),'1%');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);results.push('Binance quote and completed chart '+width);
 await page.locator('#venue').selectOption('kraken');await page.locator('#lastPrice').filter({hasText:'201 USD'}).waitFor();assert.equal(await page.locator('#dayChange').innerText(),'Not supplied');results.push('Exchange and currency switch '+width);
 fail=true;await page.locator('#venue').selectOption('binance');await page.locator('#spotStatus').filter({hasText:'Unavailable'}).waitFor();assert.equal(await page.locator('#lastPrice').innerText(),'—');assert.equal(await page.locator('#cryptoChart svg').count(),0);results.push('Failed feed clears quote and chart '+width);
 fail=false;await page.locator('#refreshCrypto').click();await page.locator('#lastPrice').filter({hasText:'101 USDT'}).waitFor();await page.locator('#refreshDelta').click();await page.locator('#deltaRows tr').waitFor();assert.match(await page.locator('#deltaRows').innerText(),/50,000/);await page.screenshot({path:'qa/crypto-'+width+'.png',fullPage:true});await page.locator('#deltaAsset').selectOption('ETH');assert.equal(await page.locator('#deltaRows tr').count(),0);results.push('Delta USD OI and contract isolation '+width);
 await page.goto(origin+'/scanner.html');await page.locator('html.auth-ready').waitFor();const end=Math.floor(Date.now()/86400000)*86400000-86400000;const lines=Array.from({length:260},(_,i)=>'TEST.NS,'+new Date(end-(259-i)*86400000).toISOString().slice(0,10)+',100,104,96,101,1000');lines[255]=lines[255].replace(',96,',',90,');lines[259]=lines[259].split(',').slice(0,2).join(',')+',98,100,92,94,1000';
 await page.locator('#historyFile').setInputFiles({name:'test.csv',mimeType:'text/csv',buffer:Buffer.from('symbol,date,open,high,low,close,volume\n'+lines.join('\n'))});await page.locator('#historyMessage').filter({hasText:'Imported 1'}).waitFor();await page.locator('#scanBtn').click();await page.locator('#resultsBody tr').waitFor();assert.match(await page.locator('#resultsBody').innerText(),/Local CSV/);assert.equal(await page.locator('#stInside').innerText(),'1');results.push('CSV scan without network feed '+width);
 assert.deepEqual(errors,[]);await ctx.close();
 }}finally{await browser.close();server.close();fs.writeFileSync('qa/crypto-results.json',JSON.stringify(results,null,2));console.log(results);}
})().catch(e=>{console.error(e);process.exitCode=1});
