const {chromium}=require('playwright');const {fixture,origin}=require('./fixtures.cjs');const path=require('path'),fs=require('fs'),assert=require('assert'),http=require('http');
(async()=>{
 const server=http.createServer((req,res)=>{let file=path.resolve('.','.'+new URL(req.url,origin).pathname);if(file.endsWith('/'))file+='index.html';try{res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.json')?'application/json':'text/html');res.end(fs.readFileSync(file));}catch(e){res.statusCode=404;res.end('Missing')}});await new Promise(r=>server.listen(8000,'127.0.0.1',r));
 const browser=await chromium.launch({headless:true,executablePath:process.env.TEST_BROWSER_PATH || undefined,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});const results=[];
 async function run(name,fn){try{await fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:e.message});}console.log(results.at(-1));}
 for(const width of [1440,390]){
 const ctx=await browser.newContext({viewport:{width,height:960}});await fixture(ctx);const page=await ctx.newPage();let errors=[];page.on('pageerror',e=>errors.push(e.message));
 await run('journal search and watchlist '+width,async()=>{await page.goto(origin+'/index.html');await page.locator('#totalIdeas').filter({hasText:'2'}).waitFor();await page.locator('#search').fill('does-not-exist');await page.locator('#ideasEmpty').waitFor({state:'visible'});await page.locator('#search').fill('TEST-A');assert.equal(await page.locator('#ideasBody tr').count(),1);if(width>600)await page.locator('#toggleWatch').click();await page.locator(width>600?'#ideasBody [data-watch]':'#mobileList [data-watch]').click();await page.locator('#watchCount').filter({hasText:'1'}).waitFor();});
 await run('performance periods '+width,async()=>{await page.goto(origin+'/performance.html');await page.locator('#closedCount').filter({hasText:'1'}).waitFor();for(const period of ['monthly','quarterly','yearly','all','weekly']){await page.locator('[data-period="'+period+'"]').click();assert.equal(await page.locator('#closedCount').innerText(),'1');}assert.equal(await page.locator('#averageReturn').innerText(),'+10.00%');});
 await run('manual setup, invalid risk, open/close paper trade '+width,async()=>{await page.goto(origin+'/setups.html');await page.locator('html.auth-ready').waitFor();await page.locator('#mSym').fill('TEST');await page.locator('#mEntry').fill('100');await page.locator('#mStop').fill('110');await page.locator('#mTarget').fill('120');await page.locator('#addManual').click();assert((await page.locator('#msg').innerText()).includes('Check direction'));await page.locator('#mStop').fill('95');await page.locator('#addManual').click();await page.locator('#riskCard').waitFor({state:'visible'});await page.locator('#rCapital').fill('-1');assert(await page.locator('#paperOpen').isDisabled());await page.locator('#rCapital').fill('100000');assert.equal(await page.locator('#oQty').innerText(),'200');await page.locator('#paperOpen').click();await page.locator('#exit-0').fill('110');await page.locator('[data-close="0"]').click();assert((await page.locator('#ledgerBody').innerText()).includes('2,000'));await page.reload();await page.locator('html.auth-ready').waitFor();await page.locator('#ledgerBody .tag.win').waitFor();});
 await run('scanner import and validation '+width,async()=>{await page.goto(origin+'/scanner.html');await page.locator('html.auth-ready').waitFor();await page.locator('#importToggle').click();await page.locator('#importBox').fill('TEST, 500325, GC=F');await page.locator('#importReplace').click();assert((await page.locator('#watchInput').inputValue()).includes('TEST.NS'));await page.locator('#watchInput').fill('');await page.locator('#scanBtn').click();assert((await page.locator('#msg').innerText()).length>0);});
 await run('fund search, comparison, scheme details '+width,async()=>{await page.goto(origin+'/funds/funds.html');await page.locator('html.auth-ready').waitFor();const search=page.locator('input[type="search"]');await search.fill('SBI');await page.waitForTimeout(200);const link=page.locator('a[href*="scheme.html?"]').first();assert(await link.isVisible());await link.click();await page.locator('html.auth-ready').waitFor();assert(!(await page.locator('main').innerText()).includes('No scheme with that code'));const compare=page.locator('a[href*="compare.html?"]').first();await compare.click();await page.locator('html.auth-ready').waitFor();assert((await page.locator('main').innerText()).includes('SBI'));});
 await run('calculator zero-return arithmetic '+width,async()=>{await page.goto(origin+'/funds/calculators.html');await page.locator('#sip-monthly').fill('1000');await page.locator('#sip-years').fill('1');await page.locator('#sip-rate').fill('0');await page.locator('#sip-stepup').fill('0');await page.locator('#lum-amount').click();assert((await page.locator('#sip-out').innerText()).includes('12,000'));});
 await run('options failure recovery '+width,async()=>{await page.goto(origin+'/gex.html');await page.locator('#mkt').filter({hasText:'UNAVAILABLE'}).waitFor();assert(await page.locator('#load').isEnabled());await page.locator('#load').click();await page.locator('#msg').filter({hasText:'Could not load'}).waitFor();assert(await page.locator('#load').isEnabled());});
 await run('navigation, theme, logout and back '+width,async()=>{await page.goto(origin+'/index.html');await page.locator('html.auth-ready').waitFor();if(width===390){await page.locator('.menu-toggle').click();assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'true');}await page.locator('[data-lfc-theme-toggle]').click();assert(await page.locator('html.theme-dark').count());await page.locator('#logoutBtn').click();await page.waitForURL('**/signin.html?loggedOut=1');assert.equal(await page.evaluate(()=>localStorage.getItem('sb-chbtjicvbezbiosuouwm-auth-token')),null);await page.goBack();await page.waitForURL('**/signin.html*');assert(await page.locator('#loginBtn').isVisible());});
 await run('zero runtime errors '+width,async()=>assert.deepEqual(errors,[]));await ctx.close();
 }
 await run('sign in honors next; stale stamp cannot authenticate',async()=>{const ctx=await browser.newContext();await fixture(ctx,false);await ctx.addInitScript(()=>localStorage.setItem('lfc.auth',JSON.stringify({u:'stale',t:Date.now()})));const p=await ctx.newPage();await p.goto(origin+'/setups.html');await p.waitForURL('**/signin.html*');await p.locator('#loginUser').fill('qa');await p.locator('#loginPass').fill('test-fixture-only');await p.locator('#loginPass').press('Enter');await p.waitForURL('**/setups.html');await p.locator('html.auth-ready').waitFor();await ctx.close();});
 await run('non-admin route and menu',async()=>{const ctx=await browser.newContext();await fixture(ctx,true,false);const p=await ctx.newPage();await p.goto(origin+'/admin.html');await p.waitForURL('**/index.html');assert(!(await p.locator('#adminNav').isVisible()));await ctx.close();});
 await run('cross-tab sign out',async()=>{const ctx=await browser.newContext();await fixture(ctx);const a=await ctx.newPage(),b=await ctx.newPage();await a.goto(origin+'/scanner.html');await b.goto(origin+'/funds/index.html');await b.locator('html.auth-ready').waitFor();await a.locator('#logoutBtn').click();await b.waitForURL('**/signin.html*');await ctx.close();});
 await run('failed revoke still clears local session',async()=>{const ctx=await browser.newContext();await fixture(ctx);await ctx.route('**/auth/v1/logout**',r=>r.abort());const p=await ctx.newPage();await p.goto(origin+'/gex.html');await p.locator('html.auth-ready').waitFor();await p.locator('#logoutBtn').click();await p.waitForURL('**/signin.html?loggedOut=1');assert.equal(await p.evaluate(()=>localStorage.getItem('sb-chbtjicvbezbiosuouwm-auth-token')),null);await ctx.close();});
 fs.writeFileSync('qa/flow-results.json',JSON.stringify(results,null,2));await browser.close();server.close();if(results.some(x=>x.status==='FAIL'))process.exitCode=1;
})();
